# Amazon US BSR Share

연도별 back 데이터 : BSR, Retail Sales (김한성수석요청)

BSR Top 20 분석
Base년도 : 2022 ~ 2023 --> 과거 Brands의 소멸 ??
1P/3P 데이터 update / AMAZON BASICS

In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import re
import math
from datetime import date

In [4]:
import os
import sys

import io
from io import BytesIO
import csv

import google.auth
from google.cloud import bigquery
#from google.cloud import bigquery_storage

In [5]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../market-analysis-project-91130-5213911f50a5.json"

credentials, project_id = google.auth.default(
    scopes=["https://www.googleapis.com/auth/cloud-platform"]
)

bqclient = bigquery.Client(credentials=credentials, project=project_id,)

In [9]:
sql = f"""
select * from wook.amz_us_bsr_add_seller_price_rating
where bsr_ctgry in ('Mattresses','Beds','Bed Frames') and rank <= 20 and bsr_date <= '2025-12-31'
"""

df_bsr = bqclient.query(sql).to_dataframe()

In [11]:
print(df_bsr)

       parent_asin   bsr_ctgry        asin  rank    bsr_date   brand  \
0       B084Q4Z5ZJ        Beds  B081HXZ5NK    17  2022-10-23  Others
1       B0B38RKRB3  Mattresses  B0827DFY3B    19  2022-10-23  Others
2       B0BSRPX3YF        Beds  B092LNV521    16  2022-10-23  Others
3       B0CSZLZM7L  Mattresses  B07ZKMYFJZ    17  2022-10-23  Others
4       B0DKFG8TSB  Bed Frames  B07C2VZ4G5    19  2022-10-23  Others
...            ...         ...         ...   ...         ...     ...
108393  B0DHRTBNV1  Bed Frames  B0CSYBPMW4     2  2024-11-12   ZINUS
108394  B0F193LJW8  Mattresses  B0CSK2VDKG     6  2024-11-12   ZINUS
108395  B0D8K4N7KM  Mattresses  B0CKYRS739    14  2024-11-12   ZINUS
108396  B0DDXJLFWD        Beds  B071JGBZYW    17  2024-11-12   ZINUS
108397  B0DYZ28XZV  Mattresses  B0CP1LR1PW     2  2024-11-12   ZINUS

       brand_raw brand_raw_org  \
0         Others        TUSEER
1         Others  S SECRETLAND
2         Others     EDENBROOK
3         Others   IYEE NATURE
4         Others     NOVOGRATZ
...          ...           ...
108393     ZINUS         ZINUS
108394     ZINUS         ZINUS
108395     ZINUS         ZINUS
108396     ZINUS         ZINUS
108397     ZINUS         ZINUS

                                                    title  \
0       Metal Bed Frame Queen Size with Vintage Headbo...
1       Full Mattress, Ssecretland 12 inch Individuall...
2       Edenbrook Delta Wood Bed Platform, California ...
3       Queen Mattress,IYEE NATURE 10 inch Gel Memory ...
4       Novogratz Bushwick Modern Metal Bed, Slightly ...
...                                                   ...
108393  Zinus Rumi 14in Queen Metal Bed Frame, Quick A...
108394  Zinus 12 Inch Green Tea Essential Memory Foam ...
108395  Zinus 6 Inch Foam and Spring Hybrid Mattress [...
108396  ZINUS Lorelei 14 Inch Metal Platform Bed Frame...
108397  Zinus 5 Inch Twin Green Tea Memory Foam Mattre...

                                                image_url  ...  date_str  \
0       https://images-na.ssl-images-amazon.com/images...  ...  10/23/22
1       https://images-na.ssl-images-amazon.com/images...  ...  10/23/22
2       https://images-na.ssl-images-amazon.com/images...  ...  10/23/22
3       https://images-na.ssl-images-amazon.com/images...  ...  10/23/22
4       https://m.media-amazon.com/images/I/91mJuy0Cnl...  ...  10/23/22
...                                                   ...  ...       ...
108393  https://m.media-amazon.com/images/I/81SmThRot8...  ...  11/12/24
108394  https://m.media-amazon.com/images/I/81fVgBVgNK...  ...  11/12/24
108395  https://m.media-amazon.com/images/I/81ZfaO6jCB...  ...  11/12/24
108396  https://m.media-amazon.com/images/I/81GjFcyC7n...  ...  11/12/24
108397  https://m.media-amazon.com/images/I/81Mk9zM-oF...  ...  11/12/24

       asin_cnt_brand_dt asin_cnt_brand_dt_rank asin_cnt_ttl_dt  \
0                     26                      0              50
1                     21                      0              50
2                     26                      0              50
3                     21                      0              50
4                     20                      0              50
...                  ...                    ...             ...
108393                 6                      1              50
108394                 5                      0              50
108395                 5                      0              50
108396                 6                      0              50
108397                 5                      0              50

        asin_cnt_ttl_dt_rank  brand_legend_ord  retail_price  rating  \
0                          0          99999999           NaN     NaN
1                          0          99999999           NaN     NaN
2                          0          99999999           NaN     NaN
3                          0          99999999           NaN     NaN
4                          0          99999999           NaN     NaN
...                      ...               ...           ...     ...
108393                     0                 0         59.99     4.6
108394                     0                 0        229.99     4.4
108395                     0                 0         89.99     4.3
108396                     0                 0         59.00     4.6
108397                     0                 0         79.00     4.4

       review_count seller_type
0               NaN        None
1               NaN        None
2               NaN        None
3               NaN        None
4               NaN        None
...             ...         ...
108393     103281.0          1P
108394      12581.0          1P
108395      29326.0          1P
108396      56905.0          1P
108397     158366.0          1P

[108398 rows x 31 columns]

# Stackline Sales
sql = f"""
select * from stck.atlas_sales_all 
where SubCategory in ('Mattresses','Beds','Bed Frames') and WeekId between 202501 and 202552
"""

df_sales = bqclient.query(sql).to_dataframe()

In [113]:
# Stackline Sales
sql = f"""
select * from stck.atlas_sales_all 
where SubCategory in ('Mattresses','Beds','Bed Frames') 
    and WeekId between 202201 and 202552
"""

df_sales = bqclient.query(sql).to_dataframe()

In [115]:
print(df_sales)

         RetailerId RetailerName RetailerSku  upc          ModelNumber  \
0                 1   Amazon.com  B09PFVMWKC  NaN                 None
1                 1   Amazon.com  B082V3R9YM  NaN                 None
2                 1   Amazon.com  B07YQRL4G5  NaN                 King
3                 1   Amazon.com  B07DC3JJXN  NaN            AR9016031
4                 1   Amazon.com  B09BJ4WMMD  NaN             AM-STT-Q
...             ...          ...         ...  ...                  ...
2967631           1   Amazon.com  B0DQ885S4N  NaN  14 in king mattress
2967632           1   Amazon.com  B0DDPQZQYB  NaN          SW-TFC4F-H2
2967633           1   Amazon.com  B0876Z43S2  NaN           MSHEBT-13Q
2967634           1   Amazon.com  B0CSFGYRHT  NaN           AOMS10QWP6
2967635           1   Amazon.com  B0DHXMG94Z  NaN         DYO-14K-BLM2

                                                     Title        Brand  \
0        14 Inch 4000lbs Heavy Duty Support Basic Bed F...      yookare
1        45MinST 18 Inch Maximum Storage Bed Frame/Rein...      45MinST
2        45MinST 18 Inch Maximum Storage Bed Frame/Rein...      45MinST
3        AFI Metro Twin XL Size Bed with Matching Footb...          AFI
4        AMOBRO Queen Bed Frame - Heavy Duty Metal Quee...       AMOBRO
...                                                    ...          ...
2967631  King Size Mattress, 14 Inch Hybrid King Mattre...   6V-Sermmoo
2967632  Sweetcrispy Tri-fold Memory Foam Mattress - 4 ...  Sweetcrispy
2967633  ZINUS 13 Inch Euro Top Pocket Spring Hybrid Ma...        Zinus
2967634  Avenco Queen 10 Inch Hybrid Mattress, Medium P...       avenco
2967635  Dyonery 14 Inch King Size Mattress in a Box, C...      Dyonery

                         Category SubCategory  WeekId  WeekEnding  \
0               Beds & Bed Frames  Bed Frames  202417  2024-04-27
1               Beds & Bed Frames  Bed Frames  202417  2024-04-27
2               Beds & Bed Frames  Bed Frames  202417  2024-04-27
3               Beds & Bed Frames  Bed Frames  202417  2024-04-27
4               Beds & Bed Frames  Bed Frames  202417  2024-04-27
...                           ...         ...     ...         ...
2967631  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967632  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967633  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967634  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967635  Mattresses & Box Springs  Mattresses  202501  2025-01-04

         RetailSales  UnitsSold  RetailPrice
0             104.99          1       104.99
1             579.96          4       144.99
2             619.96          4       154.99
3            1606.44          6       267.74
4             391.93          7        55.99
...              ...        ...          ...
2967631      2449.93          7       349.99
2967632      7084.80         80        88.56
2967633      5820.00         15       388.00
2967634      1086.60          6       181.10
2967635      1797.00          3       599.00

[2967636 rows x 14 columns]

In [19]:
df_bsr.duplicated().sum()

0

In [144]:
df1 = df_bsr.copy()

df1['bsr_date'] = pd.to_datetime(df1['bsr_date'], errors='coerce')
df1['year'] = df1['bsr_date'].dt.year
print(df1)

       parent_asin   bsr_ctgry        asin  rank   bsr_date   brand brand_raw  \
0       B084Q4Z5ZJ        Beds  B081HXZ5NK    17 2022-10-23  Others    Others
1       B0B38RKRB3  Mattresses  B0827DFY3B    19 2022-10-23  Others    Others
2       B0BSRPX3YF        Beds  B092LNV521    16 2022-10-23  Others    Others
3       B0CSZLZM7L  Mattresses  B07ZKMYFJZ    17 2022-10-23  Others    Others
4       B0DKFG8TSB  Bed Frames  B07C2VZ4G5    19 2022-10-23  Others    Others
...            ...         ...         ...   ...        ...     ...       ...
108393  B0DHRTBNV1  Bed Frames  B0CSYBPMW4     2 2024-11-12   ZINUS     ZINUS
108394  B0F193LJW8  Mattresses  B0CSK2VDKG     6 2024-11-12   ZINUS     ZINUS
108395  B0D8K4N7KM  Mattresses  B0CKYRS739    14 2024-11-12   ZINUS     ZINUS
108396  B0DDXJLFWD        Beds  B071JGBZYW    17 2024-11-12   ZINUS     ZINUS
108397  B0DYZ28XZV  Mattresses  B0CP1LR1PW     2 2024-11-12   ZINUS     ZINUS

       brand_raw_org                                              title  \
0             TUSEER  Metal Bed Frame Queen Size with Vintage Headbo...
1       S SECRETLAND  Full Mattress, Ssecretland 12 inch Individuall...
2          EDENBROOK  Edenbrook Delta Wood Bed Platform, California ...
3        IYEE NATURE  Queen Mattress,IYEE NATURE 10 inch Gel Memory ...
4          NOVOGRATZ  Novogratz Bushwick Modern Metal Bed, Slightly ...
...              ...                                                ...
108393         ZINUS  Zinus Rumi 14in Queen Metal Bed Frame, Quick A...
108394         ZINUS  Zinus 12 Inch Green Tea Essential Memory Foam ...
108395         ZINUS  Zinus 6 Inch Foam and Spring Hybrid Mattress [...
108396         ZINUS  ZINUS Lorelei 14 Inch Metal Platform Bed Frame...
108397         ZINUS  Zinus 5 Inch Twin Green Tea Memory Foam Mattre...

                                                image_url  ...  \
0       https://images-na.ssl-images-amazon.com/images...  ...
1       https://images-na.ssl-images-amazon.com/images...  ...
2       https://images-na.ssl-images-amazon.com/images...  ...
3       https://images-na.ssl-images-amazon.com/images...  ...
4       https://m.media-amazon.com/images/I/91mJuy0Cnl...  ...
...                                                   ...  ...
108393  https://m.media-amazon.com/images/I/81SmThRot8...  ...
108394  https://m.media-amazon.com/images/I/81fVgBVgNK...  ...
108395  https://m.media-amazon.com/images/I/81ZfaO6jCB...  ...
108396  https://m.media-amazon.com/images/I/81GjFcyC7n...  ...
108397  https://m.media-amazon.com/images/I/81Mk9zM-oF...  ...

       asin_cnt_brand_dt asin_cnt_brand_dt_rank asin_cnt_ttl_dt  \
0                     26                      0              50
1                     21                      0              50
2                     26                      0              50
3                     21                      0              50
4                     20                      0              50
...                  ...                    ...             ...
108393                 6                      1              50
108394                 5                      0              50
108395                 5                      0              50
108396                 6                      0              50
108397                 5                      0              50

       asin_cnt_ttl_dt_rank  brand_legend_ord  retail_price  rating  \
0                         0          99999999           NaN     NaN
1                         0          99999999           NaN     NaN
2                         0          99999999           NaN     NaN
3                         0          99999999           NaN     NaN
4                         0          99999999           NaN     NaN
...                     ...               ...           ...     ...
108393                    0                 0         59.99     4.6
108394                    0                 0        229.99     4.4
108395                    0                 0         89.99     4.3
108396                    0                 0         59.00     4.6
108397                    0                 0         79.00     4.4

        review_count seller_type  year
0                NaN        None  2022
1                NaN        None  2022
2                NaN        None  2022
3                NaN        None  2022
4                NaN        None  2022
...              ...         ...   ...
108393      103281.0          1P  2024
108394       12581.0          1P  2024
108395       29326.0          1P  2024
108396       56905.0          1P  2024
108397      158366.0          1P  2024

[108398 rows x 32 columns]

In [146]:
def get_brand_share_by_category(
    df,
    category,
    years=[2025],
    category_col='bsr_ctgry',
    brand_col='brand_raw_org',
    top_n=10,
    exclude_others=True
):
    """
    특정 category(bsr_ctgry) 기준으로
    - brand BSR 노출 수
    - category 내 brand share 계산
    - Top N 브랜드 반환
    """

    # === 1. 연도 + 카테고리 필터 ===
    df_use = df[
        (df['year'].isin(years)) &
        (df[category_col] == category)
    ].copy()

    if df_use.empty:
        print(f"[INFO] No data for category='{category}', years={years}")
        return pd.DataFrame()

    # === 2. (category, brand) BSR 노출 횟수 ===
    brand_cnt = (
        df_use
        .groupby(brand_col)
        .size()
        .reset_index(name='bsr_cnt')
    )

    # === 3. category 기준 share 계산 ===
    brand_share = (
        brand_cnt
        .assign(
            cat_total_cnt=lambda x: x['bsr_cnt'].sum(),
            bsr_share=lambda x: x['bsr_cnt'] / x['cat_total_cnt'],
            bsr_share_pct=lambda x: x['bsr_share'] * 100
        )
        .sort_values('bsr_share', ascending=False)
    )
    #print(brand_share)

    # === 5. Top N ===
    return brand_share.head(top_n)

In [148]:
categories = ['Beds', 'Bed Frames', 'Mattresses']

top10_base_2025 = {
    cat: get_brand_share_by_category(df1, category=cat, years=[2025])
    for cat in categories
}

In [150]:
top10_base_2025['Bed Frames']

    brand_raw_org  bsr_cnt  cat_total_cnt  bsr_share  bsr_share_pct
0         ALLEWIE      857           7300   0.117397      11.739726
1   AMAZON BASICS      733           7300   0.100411      10.041096
46      YAHEETECH      491           7300   0.067260       6.726027
48          ZINUS      490           7300   0.067123       6.712329
15       FURNULEM      431           7300   0.059041       5.904110
34       NEW JETO      365           7300   0.050000       5.000000
33         MELLOW      365           7300   0.050000       5.000000
27        LIKIMIO      365           7300   0.050000       5.000000
18         HLIPHA      365           7300   0.050000       5.000000
16        HAFENPO      365           7300   0.050000       5.000000

#### 1. 년도별 점유율 계산

In [152]:
# result_all 값을 기준으로 is_top10 컬럼만들기 

# Dict --> Data Frame으로 변경
rows = []
for cat, topdf in top10_base_2025.items():
    brands = topdf['brand_raw_org']
    #brands = brands.dropna().astype(str).unique().tolist()
    rows.extend([(cat, b) for b in brands])

#print(rows)

top_map = (
    pd.DataFrame(rows, columns=['bsr_ctgry', 'brand_raw_org'])
    .drop_duplicates()
)

top_map['is_top10'] = 1
print(top_map)

     bsr_ctgry        brand_raw_org  is_top10
0         Beds           SHA CERLIN         1
1         Beds               DICTAC         1
2         Beds             ADORNEVE         1
3         Beds              ALLEWIE         1
4         Beds             AMERLIFE         1
5         Beds               VINGLI         1
6         Beds               MELLOW         1
7         Beds                ZINUS         1
8         Beds             MILLIARD         1
9         Beds             JOCOEVOL         1
10  Bed Frames              ALLEWIE         1
11  Bed Frames        AMAZON BASICS         1
12  Bed Frames            YAHEETECH         1
13  Bed Frames                ZINUS         1
14  Bed Frames             FURNULEM         1
15  Bed Frames             NEW JETO         1
16  Bed Frames               MELLOW         1
17  Bed Frames              LIKIMIO         1
18  Bed Frames               HLIPHA         1
19  Bed Frames              HAFENPO         1
20  Mattresses                ZINUS         1
21  Mattresses              NOVILLA         1
22  Mattresses                MLILY         1
23  Mattresses                  FDW         1
24  Mattresses  BEST PRICE MATTRESS         1
25  Mattresses              EGOHOME         1
26  Mattresses               GAESTE         1
27  Mattresses              MOLBIUS         1
28  Mattresses             COOL GEL         1
29  Mattresses            ROLANSTAR         1

In [154]:
df_w_top = df1.merge( top_map, on=['bsr_ctgry', 'brand_raw_org'], how='left')
df_w_top['brand_new'] = df_w_top['brand_raw_org'].where(df_w_top['is_top10']==1, 'OTHERS')
print(df_w_top)

       parent_asin   bsr_ctgry        asin  rank   bsr_date   brand brand_raw  \
0       B084Q4Z5ZJ        Beds  B081HXZ5NK    17 2022-10-23  Others    Others
1       B0B38RKRB3  Mattresses  B0827DFY3B    19 2022-10-23  Others    Others
2       B0BSRPX3YF        Beds  B092LNV521    16 2022-10-23  Others    Others
3       B0CSZLZM7L  Mattresses  B07ZKMYFJZ    17 2022-10-23  Others    Others
4       B0DKFG8TSB  Bed Frames  B07C2VZ4G5    19 2022-10-23  Others    Others
...            ...         ...         ...   ...        ...     ...       ...
108393  B0DHRTBNV1  Bed Frames  B0CSYBPMW4     2 2024-11-12   ZINUS     ZINUS
108394  B0F193LJW8  Mattresses  B0CSK2VDKG     6 2024-11-12   ZINUS     ZINUS
108395  B0D8K4N7KM  Mattresses  B0CKYRS739    14 2024-11-12   ZINUS     ZINUS
108396  B0DDXJLFWD        Beds  B071JGBZYW    17 2024-11-12   ZINUS     ZINUS
108397  B0DYZ28XZV  Mattresses  B0CP1LR1PW     2 2024-11-12   ZINUS     ZINUS

       brand_raw_org                                              title  \
0             TUSEER  Metal Bed Frame Queen Size with Vintage Headbo...
1       S SECRETLAND  Full Mattress, Ssecretland 12 inch Individuall...
2          EDENBROOK  Edenbrook Delta Wood Bed Platform, California ...
3        IYEE NATURE  Queen Mattress,IYEE NATURE 10 inch Gel Memory ...
4          NOVOGRATZ  Novogratz Bushwick Modern Metal Bed, Slightly ...
...              ...                                                ...
108393         ZINUS  Zinus Rumi 14in Queen Metal Bed Frame, Quick A...
108394         ZINUS  Zinus 12 Inch Green Tea Essential Memory Foam ...
108395         ZINUS  Zinus 6 Inch Foam and Spring Hybrid Mattress [...
108396         ZINUS  ZINUS Lorelei 14 Inch Metal Platform Bed Frame...
108397         ZINUS  Zinus 5 Inch Twin Green Tea Memory Foam Mattre...

                                                image_url  ...  \
0       https://images-na.ssl-images-amazon.com/images...  ...
1       https://images-na.ssl-images-amazon.com/images...  ...
2       https://images-na.ssl-images-amazon.com/images...  ...
3       https://images-na.ssl-images-amazon.com/images...  ...
4       https://m.media-amazon.com/images/I/91mJuy0Cnl...  ...
...                                                   ...  ...
108393  https://m.media-amazon.com/images/I/81SmThRot8...  ...
108394  https://m.media-amazon.com/images/I/81fVgBVgNK...  ...
108395  https://m.media-amazon.com/images/I/81ZfaO6jCB...  ...
108396  https://m.media-amazon.com/images/I/81GjFcyC7n...  ...
108397  https://m.media-amazon.com/images/I/81Mk9zM-oF...  ...

       asin_cnt_ttl_dt asin_cnt_ttl_dt_rank brand_legend_ord retail_price  \
0                   50                    0         99999999          NaN
1                   50                    0         99999999          NaN
2                   50                    0         99999999          NaN
3                   50                    0         99999999          NaN
4                   50                    0         99999999          NaN
...                ...                  ...              ...          ...
108393              50                    0                0        59.99
108394              50                    0                0       229.99
108395              50                    0                0        89.99
108396              50                    0                0        59.00
108397              50                    0                0        79.00

        rating  review_count  seller_type  year is_top10 brand_new
0          NaN           NaN         None  2022      NaN    OTHERS
1          NaN           NaN         None  2022      NaN    OTHERS
2          NaN           NaN         None  2022      NaN    OTHERS
3          NaN           NaN         None  2022      NaN    OTHERS
4          NaN           NaN         None  2022      NaN    OTHERS
...        ...           ...          ...   ...      ...       ...
108393     4.6      103281.0           1P  2024      1.0     ZINUS
108394     4.4       12581.0           1P  2024      1.0     ZINUS
108395     4.3       29326.0           1P  2024      1.0     ZINUS
108396     4.6       56905.0           1P  2024      1.0     ZINUS
108397     4.4      158366.0           1P  2024      1.0     ZINUS

[108398 rows x 34 columns]

In [49]:
# 월별 집계하기 
brand_cnt_m = (
    df_w_top
    #.groupby(['bsr_ctgry', 'yr_month', 'brand_new'])
    .groupby(['bsr_ctgry', 'year', 'brand_new'])
    .size()
    .reset_index(name='bsr_cnt')
)

print(brand_cnt_m)

      bsr_ctgry  year      brand_new  bsr_cnt
0    Bed Frames  2021        ALLEWIE       52
1    Bed Frames  2021  AMAZON BASICS     1231
2    Bed Frames  2021         OTHERS     2668
3    Bed Frames  2021      YAHEETECH       24
4    Bed Frames  2021          ZINUS     3104
..          ...   ...            ...      ...
118  Mattresses  2025        MOLBIUS      290
119  Mattresses  2025        NOVILLA     1012
120  Mattresses  2025         OTHERS     1947
121  Mattresses  2025      ROLANSTAR      209
122  Mattresses  2025          ZINUS     1688

[123 rows x 4 columns]

In [156]:
# (category, year_month)별 분모 계산 + share
brand_share_m = (
    brand_cnt_m
    .assign(
        year_total_cnt=lambda x: x.groupby(['bsr_ctgry', 'year'])['bsr_cnt'].transform('sum'),
        bsr_share=lambda x: x['bsr_cnt'] / x['year_total_cnt'],
       # bsr_share_pct=lambda x: x['bsr_share'] * 100
    )
    .sort_values(['bsr_ctgry', 'year', 'bsr_share'], ascending=[True, True, False])
)

#brand_share_m[brand_share_m['brand_new']=='OTHERS']
print(brand_share_m[brand_share_m['bsr_ctgry']=='Bed Frames'])

     bsr_ctgry  year      brand_new  bsr_cnt  year_total_cnt  bsr_share
4   Bed Frames  2021          ZINUS     3104            7079   0.438480
2   Bed Frames  2021         OTHERS     2668            7079   0.376889
1   Bed Frames  2021  AMAZON BASICS     1231            7079   0.173895
0   Bed Frames  2021        ALLEWIE       52            7079   0.007346
3   Bed Frames  2021      YAHEETECH       24            7079   0.003390
10  Bed Frames  2022          ZINUS     3582            7220   0.496122
8   Bed Frames  2022         OTHERS     2291            7220   0.317313
6   Bed Frames  2022  AMAZON BASICS      843            7220   0.116759
9   Bed Frames  2022      YAHEETECH      353            7220   0.048892
5   Bed Frames  2022        ALLEWIE      125            7220   0.017313
7   Bed Frames  2022        LIKIMIO       26            7220   0.003601
18  Bed Frames  2023         OTHERS     3002            7300   0.411233
20  Bed Frames  2023          ZINUS     2084            7300   0.285479
12  Bed Frames  2023  AMAZON BASICS      815            7300   0.111644
11  Bed Frames  2023        ALLEWIE      439            7300   0.060137
19  Bed Frames  2023      YAHEETECH      393            7300   0.053836
17  Bed Frames  2023       NEW JETO      203            7300   0.027808
15  Bed Frames  2023        LIKIMIO      165            7300   0.022603
13  Bed Frames  2023        HAFENPO      112            7300   0.015342
16  Bed Frames  2023         MELLOW       75            7300   0.010274
14  Bed Frames  2023         HLIPHA       12            7300   0.001644
29  Bed Frames  2024         OTHERS     3132            7320   0.427869
21  Bed Frames  2024        ALLEWIE      899            7320   0.122814
31  Bed Frames  2024          ZINUS      666            7320   0.090984
22  Bed Frames  2024  AMAZON BASICS      602            7320   0.082240
26  Bed Frames  2024        LIKIMIO      366            7320   0.050000
27  Bed Frames  2024         MELLOW      366            7320   0.050000
28  Bed Frames  2024       NEW JETO      366            7320   0.050000
24  Bed Frames  2024        HAFENPO      365            7320   0.049863
30  Bed Frames  2024      YAHEETECH      360            7320   0.049180
25  Bed Frames  2024         HLIPHA      197            7320   0.026913
23  Bed Frames  2024       FURNULEM        1            7320   0.000137
40  Bed Frames  2025         OTHERS     2473            7300   0.338767
32  Bed Frames  2025        ALLEWIE      857            7300   0.117397
33  Bed Frames  2025  AMAZON BASICS      733            7300   0.100411
41  Bed Frames  2025      YAHEETECH      491            7300   0.067260
42  Bed Frames  2025          ZINUS      490            7300   0.067123
34  Bed Frames  2025       FURNULEM      431            7300   0.059041
35  Bed Frames  2025        HAFENPO      365            7300   0.050000
36  Bed Frames  2025         HLIPHA      365            7300   0.050000
37  Bed Frames  2025        LIKIMIO      365            7300   0.050000
38  Bed Frames  2025         MELLOW      365            7300   0.050000
39  Bed Frames  2025       NEW JETO      365            7300   0.050000

In [160]:
brand_share_m.to_csv('bsr_share_year_0127.csv', index=False)

#### 2. Review rating, review count, Price, 1P3P

In [11]:
df2 = df_bsr.copy()

df2['bsr_date'] = pd.to_datetime(df2['bsr_date'], errors='coerce')
df2['year'] = df2['bsr_date'].dt.year

In [13]:
print(df2)

       parent_asin   bsr_ctgry        asin  rank   bsr_date   brand brand_raw  \
0       B01L3L9WB2  Mattresses  B01L3L9WB2    15 2022-11-09  Others    Others
1       B0D5LCS7ZW        Beds  B07C2JGHCP    10 2022-11-09  Others    Others
2       B0B4LPL9HQ        Beds  B0B46NMKLX     1 2022-11-09  Others    Others
3       B0DKFG8TSB  Bed Frames  B07C2VZ4G5    18 2022-11-09  Others    Others
4       B0CB5XFRB4        Beds  B09QL28HYV    19 2022-11-09  Others    Others
...            ...         ...         ...   ...        ...     ...       ...
108393  B0D8K4N7KM  Mattresses  B0CKYRS739    12 2025-01-27   ZINUS     ZINUS
108394  B0DHRTBNV1  Bed Frames  B0CSYBPMW4    14 2025-01-27   ZINUS     ZINUS
108395  B0DYZ28XZV  Mattresses  B0CP1LR1PW     4 2025-01-27   ZINUS     ZINUS
108396  B0DNSJJBX6  Mattresses  B0CKYV45TS    17 2025-01-27   ZINUS     ZINUS
108397  B0F198BNN7  Mattresses  B0CSJTKX7K     5 2025-01-27   ZINUS     ZINUS

       brand_raw_org                                              title  \
0          HOME LIFE                  Home Life 3260Twin Mattress, Twin
1            FURINNO              FURINNO Laval Bed Frame, Queen, Stone
2             DECORO  Classic Brands Mornington 2.0 Upholstered Plat...
3          NOVOGRATZ  Novogratz Bushwick Modern Metal Bed, Slightly ...
4            IKALIDO  Ikalido Metal Loft Bed Twin Size, Multifunctio...
...              ...                                                ...
108393         ZINUS  Zinus 6 Inch Foam and Spring Hybrid Mattress [...
108394         ZINUS  Zinus Rumi 14in Queen Metal Bed Frame, Quick A...
108395         ZINUS  Zinus 5 Inch Twin Green Tea Memory Foam Mattre...
108396         ZINUS  Zinus 6 Inch Spring Sensation Hybrid Mattress ...
108397         ZINUS  Zinus 8-Inch Twin Cooling Essential Memory Foa...

                                                image_url  ...  \
0       https://images-na.ssl-images-amazon.com/images...  ...
1       https://images-na.ssl-images-amazon.com/images...  ...
2       https://images-na.ssl-images-amazon.com/images...  ...
3       https://m.media-amazon.com/images/I/91mJuy0Cnl...  ...
4       https://images-na.ssl-images-amazon.com/images...  ...
...                                                   ...  ...
108393  https://m.media-amazon.com/images/I/81ZfaO6jCB...  ...
108394  https://m.media-amazon.com/images/I/81SmThRot8...  ...
108395  https://m.media-amazon.com/images/I/81Mk9zM-oF...  ...
108396  https://m.media-amazon.com/images/I/814deK4hTd...  ...
108397  https://m.media-amazon.com/images/I/81Q3sLIqck...  ...

       asin_cnt_brand_dt asin_cnt_brand_dt_rank asin_cnt_ttl_dt  \
0                     20                      0              50
1                     27                      0              50
2                     27                      1              50
3                     17                      0              50
4                     27                      0              50
...                  ...                    ...             ...
108393                 5                      0              50
108394                 5                      0              50
108395                 5                      0              50
108396                 5                      0              50
108397                 5                      0              50

       asin_cnt_ttl_dt_rank  brand_legend_ord  retail_price  rating  \
0                         0          99999999           NaN     NaN
1                         0          99999999           NaN     NaN
2                         0          99999999           NaN     NaN
3                         0          99999999           NaN     NaN
4                         0          99999999           NaN     NaN
...                     ...               ...           ...     ...
108393                    0                 0         89.99     4.3
108394                    0                 0         59.99     4.6
108395                    0                 0         79.00     4.3
108396                    0                 0         94.99     4.2
108397                    0                 0         99.99     4.4

        review_count seller_type  year
0                NaN          3P  2022
1                NaN          3P  2022
2                NaN          3P  2022
3                NaN          3P  2022
4                NaN          3P  2022
...              ...         ...   ...
108393       29714.0          1P  2025
108394      103797.0          1P  2025
108395      160160.0          1P  2025
108396       16464.0          1P  2025
108397       13252.0          1P  2025

[108398 rows x 32 columns]

In [23]:
categories = ['Beds', 'Bed Frames', 'Mattresses']

top10_brand_2025 = {
    cat: get_brand_share_by_category(df2, category=cat, years=[2025])
    for cat in categories
}

In [27]:
#print(top10_brand_2025)
top10_brand_2025['Bed Frames']

    brand_raw_org  bsr_cnt  cat_total_cnt  bsr_share  bsr_share_pct
0         ALLEWIE      857           7300   0.117397      11.739726
1   AMAZON BASICS      733           7300   0.100411      10.041096
46      YAHEETECH      491           7300   0.067260       6.726027
48          ZINUS      490           7300   0.067123       6.712329
15       FURNULEM      431           7300   0.059041       5.904110
34       NEW JETO      365           7300   0.050000       5.000000
33         MELLOW      365           7300   0.050000       5.000000
27        LIKIMIO      365           7300   0.050000       5.000000
18         HLIPHA      365           7300   0.050000       5.000000
16        HAFENPO      365           7300   0.050000       5.000000

In [49]:
# Category별로 Top Brand의 data 추출하기
df_2025 = df2[df2['year']==2025].copy()

for cat, df_top10 in top10_brand_2025.items():
    if cat != 'Mattresses': 
        continue

    top_brands = df_top10['brand_raw_org'].unique().tolist()
    
    # ① 해당 category만 필터링
    df_cat = df_2025[df_2025['bsr_ctgry'] == cat].copy()
    if df_cat.empty:
        continue

    # ② 해당 category의 Top10 브랜드만 필터링
    df_cat_top10 = df_cat[df_cat['brand_raw_org'].isin(top_brands)].copy()

    # 동일 시간 중복이면 "마지막"이 남도록 정렬 후 tail(1)
    df_cat_top10 = df_cat_top10.sort_values(['asin', 'bsr_date'])

    #df_cat_top10[df_cat_top10['brand_raw_org']=='ZINUS'].to_csv('test_0113.csv')

    df_latest = (
        df_cat_top10
        .groupby(['bsr_ctgry','asin'], as_index=False)
        .tail(1)
    )
    
    # 1) (category, brand)별 seller_type(1P/2P/3P) ASIN 개수 → wide 형태
    seller_cnt = (
        df_latest
        .pivot_table(
            index=['bsr_ctgry', 'brand_raw_org'],
            columns='seller_type',
            values='asin',
            aggfunc=pd.Series.nunique,
            fill_value=0
        )
        .reset_index()
    )
    #print(seller_cnt)

        # 2) 평균 지표 계산
    metrics = (
        #df_latest
        df_cat_top10
        .groupby(['bsr_ctgry', 'brand_raw_org'], as_index=False)
        .agg(
            avg_rank=('rank', 'mean'),
            avg_rating=('rating', 'mean'),
            avg_retail_price=('retail_price', 'mean'),
            product_cnt=('asin', 'nunique'),   # 전체 ASIN 수(참고용)

            #seller type ratio
            seller_cnt=('seller_type', 'size'), 
            oneP_ratio=('seller_type', lambda x: (x=='1P').mean()),
            twoP_ratio=('seller_type', lambda x: (x=='2P').mean()),
            threeP_ratio=('seller_type', lambda x: (x=='3P').mean())
        )
    )
    #print(metrics)   

    # 3) 결합
    result = (
        metrics
        .merge(seller_cnt, on=['bsr_ctgry', 'brand_raw_org'], how='left')
    )

    print(result) 
    #print(f"\n==== Category: {cat} | unique_asin={df_latest['asin'].nunique()} ====\n\n")

    bsr_ctgry        brand_raw_org   avg_rank  avg_rating  avg_retail_price  \
0  Mattresses  BEST PRICE MATTRESS  10.747875    4.327616        100.499678
1  Mattresses             COOL GEL     15.048    4.455600        494.900200
2  Mattresses              EGOHOME   4.443114    4.571903        119.315378
3  Mattresses                  FDW   1.879452    4.400000         96.612521
4  Mattresses               GAESTE    7.12945    4.500324        129.954272
5  Mattresses                MLILY  14.593002    4.404972        344.252486
6  Mattresses              MOLBIUS  10.113793    4.335069        156.272222
7  Mattresses              NOVILLA  10.013834    4.431017        199.643867
8  Mattresses            ROLANSTAR  14.784689    4.611058         64.869808
9  Mattresses                ZINUS   7.244076    4.340284        141.891914

   product_cnt  seller_cnt  oneP_ratio  twoP_ratio  threeP_ratio  1P  2P  3P
0           12         353    0.915014    0.000000      0.084986   9   0   3
1            4         250    0.000000    0.000000      1.000000   0   0   4
2            6         334    0.991018    0.000000      0.008982   4   0   2
3            5         365    1.000000    0.000000      0.000000   5   0   0
4            3         309    0.000000    0.000000      1.000000   0   0   3
5            6         543    1.000000    0.000000      0.000000   6   0   0
6            4         290    0.000000    0.955172      0.044828   0   3   1
7           40        1012    0.981225    0.000000      0.018775  40   0   0
8            6         209    0.000000    0.000000      1.000000   0   0   6
9           46        1688    0.985190    0.000000      0.014810  41   0   5

#### 3. Brand별 매출

In [117]:
df3 = df_bsr.copy()

df3['bsr_date'] = pd.to_datetime(df3['bsr_date'], errors='coerce')
df3['year'] = df3['bsr_date'].dt.year

In [119]:
print(df3)

       parent_asin   bsr_ctgry        asin  rank   bsr_date   brand brand_raw  \
0       B084Q4Z5ZJ        Beds  B081HXZ5NK    17 2022-10-23  Others    Others
1       B0B38RKRB3  Mattresses  B0827DFY3B    19 2022-10-23  Others    Others
2       B0BSRPX3YF        Beds  B092LNV521    16 2022-10-23  Others    Others
3       B0CSZLZM7L  Mattresses  B07ZKMYFJZ    17 2022-10-23  Others    Others
4       B0DKFG8TSB  Bed Frames  B07C2VZ4G5    19 2022-10-23  Others    Others
...            ...         ...         ...   ...        ...     ...       ...
108393  B0DHRTBNV1  Bed Frames  B0CSYBPMW4     2 2024-11-12   ZINUS     ZINUS
108394  B0F193LJW8  Mattresses  B0CSK2VDKG     6 2024-11-12   ZINUS     ZINUS
108395  B0D8K4N7KM  Mattresses  B0CKYRS739    14 2024-11-12   ZINUS     ZINUS
108396  B0DDXJLFWD        Beds  B071JGBZYW    17 2024-11-12   ZINUS     ZINUS
108397  B0DYZ28XZV  Mattresses  B0CP1LR1PW     2 2024-11-12   ZINUS     ZINUS

       brand_raw_org                                              title  \
0             TUSEER  Metal Bed Frame Queen Size with Vintage Headbo...
1       S SECRETLAND  Full Mattress, Ssecretland 12 inch Individuall...
2          EDENBROOK  Edenbrook Delta Wood Bed Platform, California ...
3        IYEE NATURE  Queen Mattress,IYEE NATURE 10 inch Gel Memory ...
4          NOVOGRATZ  Novogratz Bushwick Modern Metal Bed, Slightly ...
...              ...                                                ...
108393         ZINUS  Zinus Rumi 14in Queen Metal Bed Frame, Quick A...
108394         ZINUS  Zinus 12 Inch Green Tea Essential Memory Foam ...
108395         ZINUS  Zinus 6 Inch Foam and Spring Hybrid Mattress [...
108396         ZINUS  ZINUS Lorelei 14 Inch Metal Platform Bed Frame...
108397         ZINUS  Zinus 5 Inch Twin Green Tea Memory Foam Mattre...

                                                image_url  ...  \
0       https://images-na.ssl-images-amazon.com/images...  ...
1       https://images-na.ssl-images-amazon.com/images...  ...
2       https://images-na.ssl-images-amazon.com/images...  ...
3       https://images-na.ssl-images-amazon.com/images...  ...
4       https://m.media-amazon.com/images/I/91mJuy0Cnl...  ...
...                                                   ...  ...
108393  https://m.media-amazon.com/images/I/81SmThRot8...  ...
108394  https://m.media-amazon.com/images/I/81fVgBVgNK...  ...
108395  https://m.media-amazon.com/images/I/81ZfaO6jCB...  ...
108396  https://m.media-amazon.com/images/I/81GjFcyC7n...  ...
108397  https://m.media-amazon.com/images/I/81Mk9zM-oF...  ...

       asin_cnt_brand_dt asin_cnt_brand_dt_rank asin_cnt_ttl_dt  \
0                     26                      0              50
1                     21                      0              50
2                     26                      0              50
3                     21                      0              50
4                     20                      0              50
...                  ...                    ...             ...
108393                 6                      1              50
108394                 5                      0              50
108395                 5                      0              50
108396                 6                      0              50
108397                 5                      0              50

       asin_cnt_ttl_dt_rank  brand_legend_ord  retail_price  rating  \
0                         0          99999999           NaN     NaN
1                         0          99999999           NaN     NaN
2                         0          99999999           NaN     NaN
3                         0          99999999           NaN     NaN
4                         0          99999999           NaN     NaN
...                     ...               ...           ...     ...
108393                    0                 0         59.99     4.6
108394                    0                 0        229.99     4.4
108395                    0                 0         89.99     4.3
108396                    0                 0         59.00     4.6
108397                    0                 0         79.00     4.4

        review_count seller_type  year
0                NaN        None  2022
1                NaN        None  2022
2                NaN        None  2022
3                NaN        None  2022
4                NaN        None  2022
...              ...         ...   ...
108393      103281.0          1P  2024
108394       12581.0          1P  2024
108395       29326.0          1P  2024
108396       56905.0          1P  2024
108397      158366.0          1P  2024

[108398 rows x 32 columns]

In [121]:
categories = ['Beds', 'Bed Frames', 'Mattresses']

top10_2025 = {
    cat: get_brand_share_by_category(df3, category=cat, years=[2025])
    for cat in categories
}

In [123]:
for cat, df_top in top10_2025.items():
    top10_2025[cat]['brand_raw_org'] = (
        df_top['brand_raw_org']
        .replace({'AMAZON BASICS': 'AMAZONBASICS'})
    )

In [125]:
top10_2025['Beds']

   brand_raw_org  bsr_cnt  cat_total_cnt  bsr_share  bsr_share_pct
59    SHA CERLIN      652           7300   0.089315       8.931507
15        DICTAC      590           7300   0.080822       8.082192
1       ADORNEVE      464           7300   0.063562       6.356164
2        ALLEWIE      389           7300   0.053288       5.328767
3       AMERLIFE      386           7300   0.052877       5.287671
72        VINGLI      383           7300   0.052466       5.246575
47        MELLOW      365           7300   0.050000       5.000000
79         ZINUS      365           7300   0.050000       5.000000
48      MILLIARD      355           7300   0.048630       4.863014
35      JOCOEVOL      345           7300   0.047260       4.726027

In [128]:
df_sales['Brand_up'] = df_sales['Brand'].str.upper().str.strip()
df_sales['Year'] = pd.to_datetime(df_sales['WeekEnding'], errors='coerce').dt.year

In [130]:
print(df_sales)

         RetailerId RetailerName RetailerSku  upc          ModelNumber  \
0                 1   Amazon.com  B09PFVMWKC  NaN                 None
1                 1   Amazon.com  B082V3R9YM  NaN                 None
2                 1   Amazon.com  B07YQRL4G5  NaN                 King
3                 1   Amazon.com  B07DC3JJXN  NaN            AR9016031
4                 1   Amazon.com  B09BJ4WMMD  NaN             AM-STT-Q
...             ...          ...         ...  ...                  ...
2967631           1   Amazon.com  B0DQ885S4N  NaN  14 in king mattress
2967632           1   Amazon.com  B0DDPQZQYB  NaN          SW-TFC4F-H2
2967633           1   Amazon.com  B0876Z43S2  NaN           MSHEBT-13Q
2967634           1   Amazon.com  B0CSFGYRHT  NaN           AOMS10QWP6
2967635           1   Amazon.com  B0DHXMG94Z  NaN         DYO-14K-BLM2

                                                     Title        Brand  \
0        14 Inch 4000lbs Heavy Duty Support Basic Bed F...      yookare
1        45MinST 18 Inch Maximum Storage Bed Frame/Rein...      45MinST
2        45MinST 18 Inch Maximum Storage Bed Frame/Rein...      45MinST
3        AFI Metro Twin XL Size Bed with Matching Footb...          AFI
4        AMOBRO Queen Bed Frame - Heavy Duty Metal Quee...       AMOBRO
...                                                    ...          ...
2967631  King Size Mattress, 14 Inch Hybrid King Mattre...   6V-Sermmoo
2967632  Sweetcrispy Tri-fold Memory Foam Mattress - 4 ...  Sweetcrispy
2967633  ZINUS 13 Inch Euro Top Pocket Spring Hybrid Ma...        Zinus
2967634  Avenco Queen 10 Inch Hybrid Mattress, Medium P...       avenco
2967635  Dyonery 14 Inch King Size Mattress in a Box, C...      Dyonery

                         Category SubCategory  WeekId  WeekEnding  \
0               Beds & Bed Frames  Bed Frames  202417  2024-04-27
1               Beds & Bed Frames  Bed Frames  202417  2024-04-27
2               Beds & Bed Frames  Bed Frames  202417  2024-04-27
3               Beds & Bed Frames  Bed Frames  202417  2024-04-27
4               Beds & Bed Frames  Bed Frames  202417  2024-04-27
...                           ...         ...     ...         ...
2967631  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967632  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967633  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967634  Mattresses & Box Springs  Mattresses  202501  2025-01-04
2967635  Mattresses & Box Springs  Mattresses  202501  2025-01-04

         RetailSales  UnitsSold  RetailPrice     Brand_up  Year
0             104.99          1       104.99      YOOKARE  2024
1             579.96          4       144.99      45MINST  2024
2             619.96          4       154.99      45MINST  2024
3            1606.44          6       267.74          AFI  2024
4             391.93          7        55.99       AMOBRO  2024
...              ...        ...          ...          ...   ...
2967631      2449.93          7       349.99   6V-SERMMOO  2025
2967632      7084.80         80        88.56  SWEETCRISPY  2025
2967633      5820.00         15       388.00        ZINUS  2025
2967634      1086.60          6       181.10       AVENCO  2025
2967635      1797.00          3       599.00      DYONERY  2025

[2967636 rows x 16 columns]

In [140]:
result_list = []   # ⭐ 결과 누적용 리스트

for cat, df_top10 in top10_2025.items():
    #if cat != 'Beds': 
    #    continue
    #df_top10['brand_raw_org'] = df['brand_raw_org'].replace({'AMAZON BASICS':'AMAZONBASICS'})

    top_brands = df_top10['brand_raw_org'].unique().tolist()
    print(top_brands)

    # ① 해당 category만 필터링
    df_cat = df_sales[df_sales['SubCategory'] == cat].copy()
    if df_cat.empty:
        continue
    
    # ② 해당 category의 Top10 브랜드만 필터링
    df_cat_top10 = df_cat[df_cat['Brand_up'].isin(top_brands)].copy()

    # 2) Brand별 매출 합
    top_brand_sales = (
        df_cat_top10
        .groupby(['SubCategory', 'Year', 'Brand_up'], as_index=False)
        .agg(
            sales=('RetailSales', 'sum'),
            qty=('UnitsSold', 'sum'),
            asins=('RetailerSku', 'nunique')
        )
        .sort_values(   
            by=['SubCategory', 'Year', 'sales'],
            ascending=[True, True, False]
        )
    )

    top_brand_sales['sales'] = top_brand_sales['sales'].map('{:,.0f}'.format)
    result_list.append(top_brand_sales)
    
    print(top_brand_sales)

# ✅ 모든 category 결과 병합
df_result = pd.concat(result_list, ignore_index=True)

['SHA CERLIN', 'DICTAC', 'ADORNEVE', 'ALLEWIE', 'AMERLIFE', 'VINGLI', 'MELLOW', 'ZINUS', 'MILLIARD', 'JOCOEVOL']
   SubCategory  Year    Brand_up        sales     qty  asins
8         Beds  2022       ZINUS  146,398,749  741416    475
6         Beds  2022  SHA CERLIN   51,802,193  300110    285
1         Beds  2022     ALLEWIE   47,235,043  249771    268
4         Beds  2022      MELLOW   18,333,672  103560     88
2         Beds  2022    AMERLIFE    4,800,577   22581     43
0         Beds  2022    ADORNEVE    3,594,131   15182     58
3         Beds  2022      DICTAC    1,707,819    7851     63
5         Beds  2022    MILLIARD      138,855    1400      2
7         Beds  2022      VINGLI       47,558     213      7
17        Beds  2023       ZINUS   91,719,519  518072    409
10        Beds  2023     ALLEWIE   68,001,443  386626    421
15        Beds  2023  SHA CERLIN   37,498,166  235705    367
11        Beds  2023    AMERLIFE   25,950,470   93796    113
13        Beds  2023      MELLOW   19,433,003  119646    107
9         Beds  2023    ADORNEVE    8,978,565   43020     76
12        Beds  2023      DICTAC    4,969,598   25498    113
14        Beds  2023    MILLIARD    1,044,695    4702      3
16        Beds  2023      VINGLI      175,697    1028      8
19        Beds  2024     ALLEWIE  118,974,458  692835    439
25        Beds  2024  SHA CERLIN   60,017,215  398377    429
27        Beds  2024       ZINUS   45,869,394  295489    370
20        Beds  2024    AMERLIFE   29,591,889  113139    525
23        Beds  2024      MELLOW   21,789,228  135709    136
21        Beds  2024      DICTAC    7,521,154   43616    130
18        Beds  2024    ADORNEVE    6,596,687   49382    148
22        Beds  2024    JOCOEVOL    1,170,185    6603     38
26        Beds  2024      VINGLI      980,673    5644     49
24        Beds  2024    MILLIARD      866,691    4072      6
29        Beds  2025     ALLEWIE  110,370,087  647645    651
35        Beds  2025  SHA CERLIN   53,619,357  376427    614
37        Beds  2025       ZINUS   30,858,221  187569    281
30        Beds  2025    AMERLIFE   25,345,052   77796    724
33        Beds  2025      MELLOW   23,436,674  161310     95
32        Beds  2025    JOCOEVOL   15,256,411   78207    192
31        Beds  2025      DICTAC   13,755,895   79070    218
28        Beds  2025    ADORNEVE   10,124,764   69373    235
36        Beds  2025      VINGLI    2,373,194   14922    155
34        Beds  2025    MILLIARD    1,164,484    4640     10
['ALLEWIE', 'AMAZONBASICS', 'YAHEETECH', 'ZINUS', 'FURNULEM', 'NEW JETO', 'MELLOW', 'LIKIMIO', 'HLIPHA', 'HAFENPO']
   SubCategory  Year      Brand_up        sales      qty  asins
7   Bed Frames  2022         ZINUS  107,582,154  1049969    402
1   Bed Frames  2022  AMAZONBASICS   62,286,781   663476     48
4   Bed Frames  2022        MELLOW    6,108,253    35713     61
0   Bed Frames  2022       ALLEWIE    3,813,368    21511     49
6   Bed Frames  2022     YAHEETECH      759,533     8770     20
3   Bed Frames  2022       LIKIMIO       94,523      687      3
5   Bed Frames  2022      NEW JETO       38,264      478      6
2   Bed Frames  2022       HAFENPO       15,121      268      3
16  Bed Frames  2023         ZINUS   64,321,687   737257    336
9   Bed Frames  2023  AMAZONBASICS   45,218,584   549986     41
14  Bed Frames  2023      NEW JETO    5,600,465    77656     24
8   Bed Frames  2023       ALLEWIE    4,319,399    26030     41
10  Bed Frames  2023       HAFENPO    3,333,206    47487     17
13  Bed Frames  2023        MELLOW    3,297,169    22883     56
15  Bed Frames  2023     YAHEETECH    1,434,363    22582     45
11  Bed Frames  2023        HLIPHA    1,130,590    15686     25
12  Bed Frames  2023       LIKIMIO      969,665     5575      9
26  Bed Frames  2024         ZINUS   34,059,449   470224    342
24  Bed Frames  2024      NEW JETO   21,916,003   365569     30
18  Bed Frames  2024  AMAZONBASICS   19,652,355   263923     36
20  Bed Frames  2024       HAFENPO   13,227,795   227014     21
17  Bed Frames  2024       ALLEWIE    7,172,726    46428     38
21  Bed Frames  2024        HLIPHA    5,228,370    98561     37
23  Bed Frames  2024        MELLOW    2,649,236    17823     86
25  Bed Frames  2024     YAHEETECH      894,763    15421     52
22  Bed Frames  2024       LIKIMIO      704,005     5010      9
19  Bed Frames  2024      FURNULEM        1,873       13      1
34  Bed Frames  2025      NEW JETO   49,969,124   889134     19
28  Bed Frames  2025  AMAZONBASICS   20,667,737   280148     36
36  Bed Frames  2025         ZINUS   19,376,067   261418    257
30  Bed Frames  2025       HAFENPO   14,880,826   275426     17
31  Bed Frames  2025        HLIPHA   11,118,036   231477     26
27  Bed Frames  2025       ALLEWIE    4,857,379    36553     41
33  Bed Frames  2025        MELLOW    2,360,798    15505     68
35  Bed Frames  2025     YAHEETECH    2,185,230    15601     28
32  Bed Frames  2025       LIKIMIO      283,407     1558      7
29  Bed Frames  2025      FURNULEM        1,234        9      1
['ZINUS', 'NOVILLA', 'MLILY', 'FDW', 'BEST PRICE MATTRESS', 'EGOHOME', 'GAESTE', 'MOLBIUS', 'COOL GEL', 'ROLANSTAR']
   SubCategory  Year             Brand_up        sales      qty  asins
5   Mattresses  2022                ZINUS  325,141,877  1354576    461
4   Mattresses  2022              NOVILLA   67,086,638   203843     46
1   Mattresses  2022             COOL GEL   50,292,881   163960     48
0   Mattresses  2022  BEST PRICE MATTRESS   19,738,846   113925     51
3   Mattresses  2022                MLILY   11,246,552    47751    203
2   Mattresses  2022                  FDW    3,661,497    25397     14
14  Mattresses  2023                ZINUS  307,508,255  1409436    410
12  Mattresses  2023              NOVILLA   84,104,935   271601    201
9   Mattresses  2023                  FDW   51,326,258   486999     26
7   Mattresses  2023             COOL GEL   29,080,407    83506     47
10  Mattresses  2023                MLILY   26,809,466    95593    265
6   Mattresses  2023  BEST PRICE MATTRESS   17,169,152   110877     74
11  Mattresses  2023              MOLBIUS      512,462     2780      8
13  Mattresses  2023            ROLANSTAR      140,784     1263     11
8   Mattresses  2023              EGOHOME        9,900       27      3
24  Mattresses  2024                ZINUS  265,029,401  1379304    457
18  Mattresses  2024                  FDW  103,571,650   710604     68
22  Mattresses  2024              NOVILLA   81,744,710   340170    420
20  Mattresses  2024                MLILY   61,271,816   220514    298
16  Mattresses  2024             COOL GEL   35,370,214   106100     47
15  Mattresses  2024  BEST PRICE MATTRESS   19,033,262   137198    103
21  Mattresses  2024              MOLBIUS    9,843,039    50155     11
19  Mattresses  2024               GAESTE    8,259,356    57351     49
23  Mattresses  2024            ROLANSTAR    6,241,833    54888     70
17  Mattresses  2024              EGOHOME    2,761,057    12368     78
34  Mattresses  2025                ZINUS  263,826,019  1611652    352
32  Mattresses  2025              NOVILLA  144,837,935   759015    686
30  Mattresses  2025                MLILY   70,791,829   231915    225
28  Mattresses  2025                  FDW   68,494,007   549184    106
27  Mattresses  2025              EGOHOME   44,551,376   393937    127
26  Mattresses  2025             COOL GEL   34,253,857   100460     47
29  Mattresses  2025               GAESTE   28,800,432   209900     47
25  Mattresses  2025  BEST PRICE MATTRESS   22,194,394   195394    108
31  Mattresses  2025              MOLBIUS   19,956,240   122778     11
33  Mattresses  2025            ROLANSTAR   10,637,370   108205     83

In [142]:
df_result.to_csv('sales_asins_year_0127.csv', index=False)